### PR TITLE
perf: use `node:` prefix to bypass require.cache call for builtins

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/nodejs/node/pull/37246/files#r588397158 and https://nodejs.org/api/modules.html#core-modules

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
Seem to be getting errors locally even on `master`.

**Comment by gurgunday** [comment]
It might be because of a test that modifies `fs`

**Comment by gurgunday** [comment]
`static.test.js` L2822

```js
t.test(
  'register with rootpath that causes statSync to fail with non-ENOENT code',
  (t) => {
    const fastifyStatic = proxyquire('../', {
      fs: {
        statSync: function statSyncStub (path) {
          throw new Error({ code: 'MOCK' })
        }
      }
    })

    const pluginOptions = {
      root: path.join(__dirname, '/static'),
      wildcard: true
    }
    const fastify = Fastify()
    fastify.register(fastifyStatic, pluginOptions)

    t.teardown(fastify.close.bind(fastify))
    fastify.listen({ port: 0 }, (err) => {
      fastify.server.unref()
      t.ok(err)
      t.end()
    })
  }
)
```

**Comment by gurgunday** [comment]
Modifying `static.test.js` (L2822) fixes the issue

```js
t.test(
  'register with rootpath that causes statSync to fail with non-ENOENT code',
  (t) => {
    const fastifyStatic = proxyquire('../', {
      'node:fs': { // HERE: fs -> 'node:fs'
        statSync: function statSyncStub (path) {
          throw new Error({ code: 'MOCK' })
        }
      }
    })

    const pluginOptions = {
      root: path.join(__dirname, '/static'),
      wildcard: true
    }
    const fastify = Fastify()
    fastify.register(fastifyStatic, pluginOptions)

    t.teardown(fastify.close.bind(fastify))
    fastify.listen({ port: 0 }, (err) => {
      fastify.server.unref()
      t.ok(err)
      t.end()
    })
  }
)
```

**Review by Eomm — APPROVED** [review]
I was today years old...

> Core modules can be identified using the node: prefix, in which case it bypasses the require cache. For instance, require('node:http') will always return the built in HTTP module, even if there is require.cache entry by that name.

Didn't know it

LGTM on green pipeline 👍🏼

**Comment by Fdawgs** [comment]
Happy to mass update rest of the repos with a similar PR at some point this weekend, unless @gurgunday beats me to it 😂

**Comment by Uzlopak** [comment]
What about prefixing npm packages with npm:? Wouldnt we then be deno compatible?

**Comment by gurgunday** [comment]
> Happy to mass update rest of the repos with a similar PR at some point this weekend, unless @gurgunday beats me to it 😂

lmaoo 🤣, no I just wanted to get the ones I actively use out of the way real fast (in case there would be release or something), I would of course prefer if you created a script for it 😁

**Review by gurgunday — APPROVED** [review]

**Comment by Fdawgs** [comment]
> What about prefixing npm packages with npm:? Wouldnt we then be deno compatible?

Can't find anything in node's documentation about supporting this?

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Fdawgs** [comment]
@mcollina happy to update Pino repos accordingly also, wdyt?

**Pull request merged**
