### PR TITLE
use fast-glob

### PR DESCRIPTION
**Pull request by gurgunday**
Ref: https://github.com/isaacs/node-glob#comparison-to-other-javascript-glob-implementations
> If you are reasonably sure that the patterns you will encounter are relatively simple, and want the absolutely fastest glob matcher out there, use [fast-glob](http://npm.im/fast-glob).

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
Given that this a module for use by a wide audience, how do you guarantee the caveat you mentioned about simple glob cases? Additionally, this is a cost paid at start up. Does it really need to be "fast" at the cost of accuracy?

**Comment by gurgunday** [comment]
I see your point, but in this case the glob pattern is [simple](https://github.com/fastify/fastify-static/blob/42b897f7be25057e7e75b95c30d74edb988e6e3f/index.js#L341C13-L341C13)

They are also both [very popular](https://npmtrends.com/fast-glob-vs-glob)

For the start-up time, we could help things with some refactoring, but at the end of the day, I just thought the API of the package was more suitable as it doesn't need to be [promisifed](https://github.com/fastify/fastify-static/pull/403/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L12) 

I don't have a strong opinion, we can leave this PR and I'll try to do some more testing and refactoring 🙏

**Comment by Eomm** [comment]
> Does it really need to be "fast" at the cost of accuracy?

Yeah, I don't think it worth. Backend's first rule:

- it must work and it must be solid

Backend's 2nd rule:

- it must be fast

**Comment by gurgunday** [comment]
These are valid concerns. Closed with comment!

**Comment by Uzlopak** [comment]
@gurgunday 

Could you have a look why glob is not upgrading?

**Pull request closed without merging**
