### PR TITLE
make type definitons `"module": "nodenext"` compatible

### PR DESCRIPTION
**Pull request by wight554**
* see https://github.com/microsoft/TypeScript/issues/48845

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
Same comment on https://github.com/fastify/fastify-cookie/pull/184#pullrequestreview-985367346

**Comment by wight554** [comment]
Any progress on this one?

**Comment by wight554** [comment]
> Thanks for opening a PR! Can you please add a unit test?

added tests from fastify-cookie, should be g2g

**Comment by mcollina** [comment]
Could you rebase on top of master?

**Comment by wight554** [comment]
> Could you rebase on top of master?

done

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@climba03003 @RafaelGSS PTAL

**Review by climba03003 — APPROVED** [review]
Although I do not like to use `namespace`.
The types here works just fine and support more area.

**Review by RafaelGSS — APPROVED** [review]
LGTM. I concur with avoiding namespaces, though.

**Comment by wight554** [comment]
> LGTM. I concur with avoiding namespaces, though.

Well Typescript rewrite with esm support might be good point for future, currently idk if there's a better way to pass current test suite

**Pull request merged**
