### PR TITLE
chore: remove handlebars

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
Is there a reason?

**Comment by Uzlopak** [comment]
@jsumners 

the handlebars test does not make any sense, and is more like a handlebars test than a fastify-static test.

**Review by gurgunday — COMMENTED** [review]
I get the test part but the example without a template engine is dangerous as if a file name contains `"` or a special HTML char, the template in this example would break

Even if it would be fine here, it's not a good practice to show it as an example I think

**Comment by Uzlopak** [comment]
Maybe, but even we are not using handlebars in our implementation of fastifystatic

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]

**Pull request merged**
