### PR TITLE
Fix custom not found error for v2

### LINKED ISSUE #77: setNotFoundHandler is broken with Fastify v2
I checked a bit and couldn't understand what the problem might be. I played around with the tests of `setNotFoundHandler` in main Fastify repo and they seem to be good. 

Any ideas what might be wrong?

https://github.com/fastify/fastify-static/blob/master/test/static.test.js#L362

```
  not found responses can be customized with fastify.setNotFoundHandler() > /path/does/not/exist.html
  not ok should be equal
    +++ found
    --- wanted
    -text/plain
    +application/json; charset=utf-8
    compare: ===

  not found responses can be customized with fastify.setNotFoundHandler() > /path/does/not/exist.html
  not ok should be equal
    +++ found
    --- wanted
    -/path/does/not/exist.html Not Found
    +{"statusCode":404,"code":"ENOENT","error":"Not Found","message":"ENOENT: no such file or directory, stat 'C:\\Users\\cemre.mengu\\Desktop\\fastify-static\\test\\static\\path\\does\\not\\exist.html'"}
    compare: ===
```

### PR DESCRIPTION
**Pull request by cemremengu**
~~I wanted to preserve backwards compatibility~~

Closes #77

### CODE REVIEW

**Comment by cemremengu** [comment]
We really need a way run tests both on `1.x` and `2.x` versions at the same time

**Comment by cemremengu** [comment]
@allevo brought this up first in one of the issues as a concern. I think we should decide on a common/consistent procedure when an official plugin breaks between Fastify versions as part of the LTS support.

**Comment by mcollina** [comment]
Official plugins should follow the same LTS policy of fastify. As an example, we should support a version that runs on Fastify v1 as long as it is supported.

**Comment by cemremengu** [comment]
@mcollina we should create a `1.x` branch for broken plugins then. Would that be a feasible/sensible thing to do?

**Comment by cemremengu** [comment]
Great, I am +1 for applying this to other broken plugins as well. @fastify/fastify any comments/objections to this approach?

**Pull request merged**
