### PR TITLE
Add windows testing

### PR DESCRIPTION
**Pull request by cemremengu**

### CODE REVIEW

**Comment by mcollina** [comment]
@cemremengu if you have time, release after landing this :)

**Comment by cemremengu** [comment]
@mcollina sure, will do!

**Comment by cemremengu** [comment]
Closing in favor of #85

**Comment by mcollina** [comment]
I think next is still ok

Il giorno sab 5 gen 2019 alle 17:28 Cemre Mengu <notifications@github.com>
ha scritto:

**Pull request closed without merging**
