### PR TITLE
Fix type of dotfiles property

### LINKED ISSUE #165: Wrong type for option dotfiles
https://github.com/fastify/fastify-static/blob/1f6806c47ab1e8eb6b7468856835b00772e2d91f/index.d.ts#L48

See: https://www.npmjs.com/package/send#dotfiles dotfiles is string and possible options are `'allow' | 'deny' | 'ignore'`

### PR DESCRIPTION
**Pull request by MSE99**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

#### Note

Fixes #165

### CODE REVIEW

**Comment by zekth** [comment]
can you add test for dotfile? thanks

**Comment by mcollina** [comment]
See https://github.com/fastify/fastify-static/blob/master/test/types/index.ts for the test

**Comment by MSE99** [comment]
The CI failed, it's because the tests failed due to the fact i tried to dynamically add an `.example` file for each test (it worked and the tests passed on my local machine) i did this because i didn't want to conflict with the last pull request since adding a file to the `static` directory will require editing other test, since this branch is behind master can i merge the changes from master into it and just manually add the `.example` file into the `static` directory ?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by zekth — APPROVED** [review]
lgtm. Thanks for adding the tests

**Pull request merged**
