### PR TITLE
Upgrade glob to v10

### PR DESCRIPTION
**Pull request by gurgunday**
What changed: glob is stricter in its syntax so we have to escape characters more consistently

Closes: #402

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by gurgunday** [comment]
Damn it actually worked 🤣

This should merge after #405

**Comment by gurgunday** [comment]
Not sure about the license check that failed, only `glob` was updated

**Comment by Eomm** [comment]
We may add it to the workflow:

https://github.com/isaacs/jackspeak/issues/7

**Comment by gurgunday** [comment]
If we mark this as semver major (I don't see the need), I would like to use `replaceAll` with strings instead of regex

**Comment by gurgunday** [comment]
> We may add it to the workflow:
> 
> [isaacs/jackspeak#7](https://github.com/isaacs/jackspeak/issues/7)

@Eomm how can we do that?

**Comment by Uzlopak** [comment]
Seems to be a hornet nest :(

https://writing.kemitchell.com/2019/05/05/Rely-on-OSI.html
https://github.com/angular/angular-cli/issues/25387

**Comment by gurgunday** [comment]
Looks like a cool license 🤠

**Review by mcollina — CHANGES_REQUESTED** [review]
This is one thing I'll put a temporary -1 on. I would need to check with the OpenJS Lawyers about this.

According to the OpenJS IP policy we cannot use BlueOak-1.0.0 https://openjsf.org/wp-content/uploads/sites/84/2019/10/OpenJS-Foundation-IP-Policy-2019-10-22.pdf.

**Comment by gurgunday** [comment]
Oh, I didn't know that, no problem!

**Comment by jsumners** [comment]
> This is one thing I'll put a temporary -1 on. I would need to check with the OpenJS Lawyers about this.
> 
> According to the OpenJS IP policy we cannot use BlueOak-1.0.0 [openjsf.org/wp-content/uploads/sites/84/2019/10/OpenJS-Foundation-IP-Policy-2019-10-22.pdf](https://openjsf.org/wp-content/uploads/sites/84/2019/10/OpenJS-Foundation-IP-Policy-2019-10-22.pdf).

Wait, what? Why isn't BlueOak acceptable?

**Comment by mcollina** [comment]
It's not OSI approved (by design). Trying to get a new OSS license through a major company legal department is _very hard_ and that rule account for that. Note that we have the license checker since before we went into openjs exactly for this reason.

**Comment by gurgunday** [comment]
@mcollina is BSD-2-Clause-Patent acceptable in your opinion?

**Comment by Uzlopak** [comment]
@gurgunday 

https://github.com/fastify/workflows/blob/704b2c8d932efd159e3f28f64a535fe4bf423d92/.github/workflows/plugins-ci.yml#L66

**Comment by gurgunday** [comment]
I know about the workflow, I'm just asking if, according to OpenJS Foundation policy, `BSD-2-Clause-Patent` could be considered as `BSD-2-Clause`


I'd say no but just wanted to make sure

**Comment by mcollina** [comment]
what library is using that license?

**Comment by gurgunday** [comment]
None that I know of

I asked because I was considering creating a faster glob implementation that is as correct as `node-glob` and wanted to make a more informed decision on the License

**Comment by gurgunday** [comment]
This can merge now

**Comment by Uzlopak** [comment]
@gurgunday Can you add blue oak to the workflows?

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
