### PR TITLE
fix: follow symlink subdir without wildcard

### LINKED ISSUE #185: Symbolic-Link doesn't work without wildcard
## 🐛 Bug Report

Symbolic link doesn't work if I set `wildcard: false`.

## To Reproduce

1 - add a `symbolic-link` in your `public` directory: `cd public && ln -s ../assets assets`
2 - set `wildcard: false`

```js
await server.register(fastifyStatic, { root: [path.join(__dirname, 'public')], wildcard: false });
```

## Expected behavior

`fastify-static` should `serve` the content inside the `symbolic-link` if `wildcard: false`.

## Your Environment

- *node version*: 14.15.1
- *fastify version*: >=3.14.0
- *os*: Mac

### PR DESCRIPTION
**Pull request by is2ei**
fixes #185

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]
Is this a major?

PS: could @is2ei fix the conflicts?

**Comment by is2ei** [comment]
@Eomm 
I fixed it 🔧

**Comment by mcollina** [comment]
I don't think so! Should be a nminor.

**Pull request merged**
